"""Added transaction table

Revision ID: 07e5a1d3b034
Revises: e175b39b1b03
Create Date: 2020-06-30 13:05:45.871104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e5a1d3b034'
down_revision = 'e175b39b1b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=35), nullable=False),
    sa.Column('destination', sa.String(length=35), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination'], ['wallet.address'], ),
    sa.ForeignKeyConstraint(['source'], ['wallet.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.create_index(op.f('ix_wallet_address'), 'wallet', ['address'], unique=True)
    op.drop_constraint('wallet_address_key', 'wallet', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wallet_address_key', 'wallet', ['address'])
    op.drop_index(op.f('ix_wallet_address'), table_name='wallet')
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('transaction')
    # ### end Alembic commands ###
