"""Added wallet table.

Revision ID: e175b39b1b03
Revises: 26b1d07426cb
Create Date: 2020-06-29 14:40:15.760648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e175b39b1b03'
down_revision = '26b1d07426cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.String(length=130), nullable=False),
    sa.Column('address', sa.String(length=35), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_table('wallet')
    # ### end Alembic commands ###
